### ISSUE TITLE
Error with object-observer

### ISSUE THREAD

**Issue by kleveland** [easybase/easybase-react#1]
`is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename object-observer.min.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from`
I am using nextron (nextjs + react). Any ideas?

**Comment by dilan-dio4** [comment]
Hello Kacey.

I'm not too familiar with the Election framework, but I do think I have come up with a solution for your use case.

Instead of importing `EasybaseProvider` and `useEasybase` the traditional way:
```jsx
```

**Comment by dilan-dio4** [comment]
Hello Kacey.

I'm not too familiar with the Electron framework, but I do think I have a solution for your use case.

Instead of importing `EasybaseProvider` and `useEasybase` the traditional way:
```jsx
import { EasybaseProvider, useEasybase } from 'easybase-react';
```

Use the **dynamic** loader, provided by Next.js.
```jsx
import dynamic from 'next/dynamic';
import { useEasybase } from 'easybase-react';

const DynamicEasybaseProvider = dynamic(
  () => import("easybase-react").then((mod) => mod.EasybaseProvider),
  { ssr: false }
);
```
From there you can use `DynamicEasybaseProvider` as would `EasybaseProvider`. [Read more about dynamic here](https://nextjs.org/docs/advanced-features/dynamic-import).

So, a full using nextron would look like:

```jsx
import React from 'react';
import dynamic from 'next/dynamic';
import ebconfig from "../ebconfig";
import { useEasybase } from 'easybase-react';

const DynamicEasybaseProvider = dynamic(
  () => import("easybase-react").then((mod) => mod.EasybaseProvider),
  { ssr: false }
);

const Home = () => {
  return (
      <DynamicEasybaseProvider ebconfig={ebconfig}>
        <Printer />
      </DynamicEasybaseProvider>
  );
};

const Printer = () => {
  const { configureFrame, sync, Frame } = useEasybase();

  React.useEffect(() => {
    configureFrame({ limit: 10, offset: 0 });
    sync();
  }, [])

  return (
    <div>
      {Frame().map(ele => <p>{JSON.stringify(ele)}</p>)}
    </div>
  )
}

export default Home;
```

If you could, let me know if this works for you. I'm sure there exists a solution for using easybase-react with Nextron.

**Comment by kleveland** [comment]
Thank you for the detailed response! I actually switched gears to using an electron react boiler plate and it seems to work fine there. Hopefully if someone uses nextron in the future they can use your solution though!
